### ISSUE TITLE
Question about customization

### ISSUE THREAD

**Issue by traed** [DanielDent/docker-nginx-ssl-proxy#4]
First off, thanks for a great project!

I have a question about the customization topic in the readme. How come creating a new Dockerfile and copying in the proxy.conf is the preferred way over say a volume? Is there a downside to using a volume or is it just preference?

**Comment by DanielDent** [comment]
You are most welcome.

The question of what configuration is best kept as runtime data vs kept as part of the docker image really depends on how you are using Docker.

I don't remember any specific reason I recommended that approach. Based on a quick review I think a volume would work just fine.

I may have written that because docker volumes can have non-intuitive behaviours in terms of how they do/don't get initialized, and I may have been trying to avoid a long writeup on the various cases of how docker volumes work.

Please feel free to re-open if you have further questions.
